drop table P_USER if exists;

CREATE TABLE P_USER
(
    ID         INT IDENTITY PRIMARY KEY,
    USERNAME   VARCHAR2(50) NOT NULL,
    PASSWORD   VARCHAR2(50) NOT NULL,
    EMAIL      VARCHAR2(50) NOT NULL,
    UNIQUE (EMAIL),
    UNIQUE (USERNAME)
);
